/**
 * GET /progress-report/[id]  (AI-7489)
 *
 * Renders the saved HTML founder progress report for the owning user.
 * Server-side rendered for speed. The HTML is generated by our own renderer
 * from escaped, trusted data (no raw model HTML), so dangerouslySetInnerHTML
 * is safe here.
 */

import { notFound, redirect } from "next/navigation";
import { getOptionalUserId } from "@/lib/auth";
import { createServiceClient } from "@/lib/supabase/server";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function ProgressReportPage({ params }: PageProps) {
  const { id } = await params;
  const userId = await getOptionalUserId();

  if (!userId) {
    redirect(`/login?next=/progress-report/${id}`);
  }

  const supabase = createServiceClient();
  const { data: report } = await supabase
    .from("founder_progress_reports")
    .select("user_id, html, generation_status")
    .eq("id", id)
    .maybeSingle();

  if (!report) notFound();
  if ((report as { user_id: string }).user_id !== userId) notFound();

  const status = (report as { generation_status: string }).generation_status;
  if (status !== "completed") {
    return (
      <div style={{ padding: 48, fontFamily: "system-ui", textAlign: "center" }}>
        <h1>Your progress report is still generating...</h1>
        <p>This usually takes 10-20 seconds. Refresh in a moment.</p>
      </div>
    );
  }

  const html = (report as { html: string }).html;

  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
