/**
 * PDF Export Utility
 * Phase 03: Pro Tier Features
 *
 * Generates PDF documents from strategy document content
 * using @react-pdf/renderer with React.createElement (no JSX in .ts).
 */

import React from 'react';
import {
  renderToBuffer,
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';

// ============================================================================
// Styles
// ============================================================================

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.5,
    color: '#333333',
  },
  titlePage: {
    padding: 50,
    fontFamily: 'Helvetica',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  titleText: {
    fontSize: 24,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#1a1a1a',
  },
  titleDate: {
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 10,
  },
  titleBranding: {
    fontSize: 10,
    color: '#ff6a1a',
    textAlign: 'center',
    marginTop: 40,
  },
  sectionHeading: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 10,
    marginTop: 20,
    color: '#1a1a1a',
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.5,
    marginBottom: 8,
    color: '#333333',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 50,
    right: 50,
    fontSize: 8,
    color: '#999999',
    textAlign: 'center',
  },
});

// ============================================================================
// PDF Export
// ============================================================================

interface ExportInput {
  title: string;
  content: string;
  sections: Array<{ title: string; content: string }>;
}

/**
 * Generate a PDF buffer from a strategy document.
 */
export async function exportToPDF(doc: ExportInput): Promise<Buffer> {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Build title page
  const titlePage = React.createElement(
    Page,
    { size: 'A4', style: styles.titlePage },
    React.createElement(
      View,
      { style: { flex: 1, justifyContent: 'center', alignItems: 'center' } },
      React.createElement(Text, { style: styles.titleText }, doc.title),
      React.createElement(Text, { style: styles.titleDate }, today),
      React.createElement(
        Text,
        { style: styles.titleBranding },
        'Generated by FRED | Sierra Ventures'
      )
    )
  );

  // Build content pages with sections
  const sectionElements: React.ReactElement[] = [];
  for (const section of doc.sections) {
    sectionElements.push(
      React.createElement(
        Text,
        { style: styles.sectionHeading, key: `heading-${section.title}` },
        section.title
      )
    );

    // Split content into paragraphs
    const paragraphs = section.content.split('\n\n').filter((p) => p.trim());
    for (let i = 0; i < paragraphs.length; i++) {
      sectionElements.push(
        React.createElement(
          Text,
          { style: styles.paragraph, key: `para-${section.title}-${i}` },
          paragraphs[i].trim()
        )
      );
    }
  }

  const contentPage = React.createElement(
    Page,
    { size: 'A4', style: styles.page, wrap: true },
    ...sectionElements,
    React.createElement(
      Text,
      { style: styles.footer, fixed: true },
      `${doc.title} | Generated by FRED`
    )
  );

  // Build the document
  const pdfDocument = React.createElement(
    Document,
    { title: doc.title, author: 'FRED by Sierra Ventures' },
    titlePage,
    contentPage
  );

  const buffer = await renderToBuffer(pdfDocument);
  return Buffer.from(buffer);
}
