/**
 * GET /reports/[id]
 *
 * Renders the saved HTML report for the owning user (or anyone with the
 * public_share_token, future enhancement). Server-side rendered for SEO + speed.
 */

import { notFound, redirect } from "next/navigation";
import { getOptionalUserId } from "@/lib/auth";
import { createServiceClient } from "@/lib/supabase/server";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function ReportPage({ params }: PageProps) {
  const { id } = await params;
  const userId = await getOptionalUserId();

  if (!userId) {
    redirect(`/login?next=/reports/${id}`);
  }

  const supabase = createServiceClient();
  const { data: report } = await supabase
    .from("founder_reports")
    .select("user_id, html, generation_status")
    .eq("id", id)
    .maybeSingle();

  if (!report) notFound();
  if ((report as { user_id: string }).user_id !== userId) notFound();

  const status = (report as { generation_status: string }).generation_status;
  if (status !== "completed") {
    return (
      <div style={{ padding: 48, fontFamily: "system-ui", textAlign: "center" }}>
        <h1>Your report is still generating...</h1>
        <p>This usually takes 10-20 seconds. Refresh in a moment.</p>
      </div>
    );
  }

  const html = (report as { html: string }).html;

  return (
    <div
      // The HTML is server-generated by us from a trusted Claude payload.
      // It contains only inline styles + escaped content from our renderer.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
