/**
 * Dashboard Export API
 *
 * GET /api/dashboard/export
 * Generates a PDF report with momentum and trends data.
 * Uses @react-pdf/renderer with React.createElement (no JSX in .ts).
 */

import React from "react";
import { NextResponse } from "next/server";
import {
  renderToBuffer,
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { requireAuth } from "@/lib/auth";
import { getFounderTrends } from "@/lib/dashboard/trends";
import { computeMomentumIndicator } from "@/lib/dashboard/engagement-score";

// ============================================================================
// Styles
// ============================================================================

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontFamily: "Helvetica",
    fontSize: 11,
    lineHeight: 1.5,
    color: "#333333",
  },
  titlePage: {
    padding: 50,
    fontFamily: "Helvetica",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  titleText: {
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    marginBottom: 20,
    color: "#1a1a1a",
  },
  titleDate: {
    fontSize: 12,
    color: "#666666",
    textAlign: "center",
    marginBottom: 10,
  },
  titleBranding: {
    fontSize: 10,
    color: "#ff6a1a",
    textAlign: "center",
    marginTop: 40,
  },
  sectionHeading: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginBottom: 10,
    marginTop: 20,
    color: "#1a1a1a",
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.5,
    marginBottom: 8,
    color: "#333333",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingVertical: 4,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderBottomColor: "#1a1a1a",
    paddingVertical: 4,
    marginBottom: 2,
  },
  tableCell: {
    flex: 1,
    fontSize: 9,
    color: "#333333",
  },
  tableCellHeader: {
    flex: 1,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#1a1a1a",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    fontSize: 8,
    color: "#999999",
    textAlign: "center",
  },
});

export async function GET() {
  try {
    const userId = await requireAuth();

    // Fetch data server-side (no HTTP round-trip)
    const [trends, momentum] = await Promise.all([
      getFounderTrends(userId, "weekly", 12), // 90 days max to avoid timeout
      computeMomentumIndicator(userId),
    ]);

    const today = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    // Title page
    const titlePage = React.createElement(
      Page,
      { size: "A4", style: styles.titlePage },
      React.createElement(
        View,
        {
          style: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
          },
        },
        React.createElement(
          Text,
          { style: styles.titleText },
          "Founder Analytics Report"
        ),
        React.createElement(Text, { style: styles.titleDate }, today),
        React.createElement(
          Text,
          { style: styles.titleBranding },
          "Generated by FRED | Sierra Ventures"
        )
      )
    );

    // Momentum section elements
    const momentumElements = [
      React.createElement(
        Text,
        { style: styles.sectionHeading, key: "momentum-heading" },
        "Momentum"
      ),
      React.createElement(
        Text,
        { style: styles.paragraph, key: "momentum-trend" },
        `Trend: ${momentum.trend.charAt(0).toUpperCase() + momentum.trend.slice(1)}`
      ),
      React.createElement(
        Text,
        { style: styles.paragraph, key: "momentum-summary" },
        momentum.summary
      ),
    ];

    // Trends table elements
    const trendsElements: React.ReactElement[] = [
      React.createElement(
        Text,
        { style: styles.sectionHeading, key: "trends-heading" },
        "Activity Trends"
      ),
    ];

    // Table header
    const headers = [
      "Period",
      "Conversations",
      "Check-Ins",
      "Steps Done",
      "Decisions",
      "Docs",
    ];
    trendsElements.push(
      React.createElement(
        View,
        { style: styles.tableHeader, key: "table-header" },
        ...headers.map((h) =>
          React.createElement(
            Text,
            { style: styles.tableCellHeader, key: `h-${h}` },
            h
          )
        )
      )
    );

    // Table rows
    for (const row of trends) {
      trendsElements.push(
        React.createElement(
          View,
          { style: styles.tableRow, key: `row-${row.period}` },
          React.createElement(
            Text,
            { style: styles.tableCell, key: `${row.period}-p` },
            row.period
          ),
          React.createElement(
            Text,
            { style: styles.tableCell, key: `${row.period}-c` },
            String(row.conversations)
          ),
          React.createElement(
            Text,
            { style: styles.tableCell, key: `${row.period}-ci` },
            String(row.checkIns)
          ),
          React.createElement(
            Text,
            { style: styles.tableCell, key: `${row.period}-ns` },
            String(row.nextStepsCompleted)
          ),
          React.createElement(
            Text,
            { style: styles.tableCell, key: `${row.period}-ds` },
            String(row.decisionsScored)
          ),
          React.createElement(
            Text,
            { style: styles.tableCell, key: `${row.period}-dc` },
            String(row.documentsCreated)
          )
        )
      );
    }

    if (trends.length === 0) {
      trendsElements.push(
        React.createElement(
          Text,
          { style: styles.paragraph, key: "no-trends" },
          "No activity data available yet."
        )
      );
    }

    // Wrap all content in a View to avoid mixed element type errors
    const contentView = React.createElement(
      View,
      { key: "content-wrapper" },
      ...momentumElements,
      ...trendsElements
    );

    // Content page
    const contentPage = React.createElement(
      Page,
      { size: "A4", style: styles.page, wrap: true },
      contentView,
      React.createElement(
        Text,
        { style: styles.footer, fixed: true },
        "Founder Analytics Report | Generated by FRED"
      )
    );

    // Build document
    const pdfDocument = React.createElement(
      Document,
      { title: "Founder Analytics Report", author: "FRED by Sierra Ventures" },
      titlePage,
      contentPage
    );

    const buffer = await renderToBuffer(pdfDocument);

    return new Response(Buffer.from(buffer), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition":
          'attachment; filename="founder-analytics-report.pdf"',
      },
    });
  } catch (error) {
    if (error instanceof Response) {
      return error;
    }

    console.error("[Export API] Error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to generate PDF export" },
      { status: 500 }
    );
  }
}
