#!/usr/bin/env npx tsx
/**
 * CLI: Generate Mobile Test Checklist
 *
 * Phase 90: User Testing Loop
 * Generates a markdown checklist file for mobile device testing.
 *
 * Usage:
 *   npx tsx scripts/mobile-test-checklist.ts
 *
 * Output:
 *   docs/mobile-test-checklist.md
 */

import { writeFileSync, mkdirSync, existsSync } from "fs"
import { join } from "path"

const CHECKLIST = `# Mobile Testing Protocol

> Generated by \`npx tsx scripts/mobile-test-checklist.ts\`
> Last updated: ${new Date().toISOString().slice(0, 10)}

## Device Matrix

- [ ] iPhone 14/15 (Safari)
- [ ] iPhone 14/15 (Chrome)
- [ ] Android (Samsung Galaxy S23, Chrome)
- [ ] iPad (Safari, landscape + portrait)

---

## Critical Flows

### 1. Event Landing (/event/palo-alto-2026)

- [ ] QR code scan loads page < 3s
- [ ] No horizontal scroll
- [ ] Signup form usable with thumb
- [ ] Password field shows/hides
- [ ] Error states visible (invalid email, short password)
- [ ] Social proof section renders correctly
- [ ] CTA buttons are tappable and properly sized

### 2. Onboarding (/get-started)

- [ ] All steps navigable via swipe or tap
- [ ] Stage selection tappable (radio buttons / cards)
- [ ] Progress indicator visible and accurate
- [ ] Can complete full onboarding in < 2 minutes
- [ ] Free-text inputs work with mobile keyboard
- [ ] Back button returns to previous step
- [ ] Skip/optional fields clearly marked

### 3. Dashboard (/dashboard)

- [ ] All cards render without overflow
- [ ] Navigation menu accessible (hamburger or bottom nav)
- [ ] Charts and graphs render on mobile viewport
- [ ] Oases journey visualizer scrollable
- [ ] Score cards readable on small screen
- [ ] Quick actions tappable
- [ ] Pull-to-refresh works if applicable

### 4. FRED Chat (/chat)

- [ ] Input field stays above keyboard when focused
- [ ] Messages scrollable (no stuck scroll)
- [ ] Send button tappable (>= 44px touch target)
- [ ] Response renders within 5s
- [ ] Long messages wrap correctly
- [ ] Code blocks / formatted text readable
- [ ] Thumbs up/down feedback widgets tappable
- [ ] Chat history loads on return

### 5. Documents Upload (/dashboard/documents)

- [ ] File picker opens on mobile (native file browser)
- [ ] Upload progress visible
- [ ] Drag & drop zone indicates tap-to-upload on mobile
- [ ] Score card readable on small screen
- [ ] Dimension bars render correctly
- [ ] Suggestions expandable via tap
- [ ] "Upload Another" button accessible

### 6. Voice Coaching (/dashboard/voice)

- [ ] Microphone permission prompt appears
- [ ] Voice connection establishes < 5s
- [ ] Audio plays through device speaker
- [ ] Mute/unmute button responsive
- [ ] End call button prominent
- [ ] Transcript displays in real-time
- [ ] Works with Bluetooth headphones

### 7. Pricing Page (/pricing)

- [ ] All tier cards visible (may need horizontal scroll)
- [ ] Feature comparison readable
- [ ] CTA buttons tappable
- [ ] Price displayed clearly
- [ ] Toggle monthly/annual if applicable

---

## Performance Benchmarks

- [ ] LCP (Largest Contentful Paint) < 2.5s on 4G
- [ ] FID (First Input Delay) < 100ms
- [ ] CLS (Cumulative Layout Shift) < 0.1
- [ ] No layout shift on page load
- [ ] Touch targets >= 44px (Apple HIG) / 48dp (Material Design)
- [ ] No janky scroll on any page
- [ ] Images lazy-load below the fold

---

## Accessibility

- [ ] Text readable without zooming (minimum 16px body text)
- [ ] Sufficient color contrast (4.5:1 ratio minimum)
- [ ] Focus indicators visible on interactive elements
- [ ] Screen reader announces page changes
- [ ] Form labels associated with inputs

---

## Pass/Fail Summary

| Flow | iPhone Safari | iPhone Chrome | Android Chrome | iPad Safari |
|------|:---:|:---:|:---:|:---:|
| Event Landing | | | | |
| Onboarding | | | | |
| Dashboard | | | | |
| FRED Chat | | | | |
| Documents Upload | | | | |
| Voice Coaching | | | | |
| Pricing | | | | |

### Legend
- **P** = Pass
- **F** = Fail (note issue below)
- **N/A** = Not applicable

---

## Issues Found

| # | Flow | Device | Description | Severity | Phase to Fix |
|---|------|--------|-------------|----------|-------------|
| 1 | | | | | |
| 2 | | | | | |
| 3 | | | | | |

### Severity Levels
- **Critical**: Blocks user from completing flow
- **Major**: Significantly degrades experience
- **Minor**: Cosmetic or minor usability issue

---

## Sign-off

| Tester | Date | Device(s) Tested | Overall Status |
|--------|------|-------------------|---------------|
| | | | |
`

function main() {
  const projectRoot = join(__dirname, "..")
  const docsDir = join(projectRoot, "docs")

  // Ensure docs directory exists
  if (!existsSync(docsDir)) {
    mkdirSync(docsDir, { recursive: true })
  }

  const outputPath = join(docsDir, "mobile-test-checklist.md")
  writeFileSync(outputPath, CHECKLIST, "utf-8")

  console.log(`Mobile test checklist generated at: ${outputPath}`)
  console.log(`Covers ${7} critical flows across ${4} device types.`)
}

main()
