/**
 * IdeaPros ~120-Step Journey Template
 *
 * AI-1802: Maps the IdeaPros venture-building process (~120 steps) to
 * Sahara's 5 Oases stages. Each step has an ID, label, description,
 * stage assignment, ordering within its stage, and completion criteria.
 *
 * Based on IdeaPros methodology: a structured, sequential process that
 * prevents founders from skipping ahead. Users must complete steps in
 * order within each stage before advancing.
 *
 * Stage distribution: Clarity (20) + Validation (25) + Build (30) + Launch (25) + Grow (20) = 120
 */

import type { OasesStage } from "@/types/oases"

export interface JourneyStep {
  id: string
  stage: OasesStage
  order: number
  label: string
  description: string
  category: string
  completionCriteria: string
  estimatedMinutes: number
  /** Whether this step requires FRED interaction */
  requiresFred: boolean
  /** Whether this step can be auto-completed by the platform */
  autoComplete: boolean
}

// ---------------------------------------------------------------------------
// Stage 1: CLARITY (20 steps)
// Focus: Self-assessment, idea articulation, founder readiness
// ---------------------------------------------------------------------------

const claritySteps: JourneyStep[] = [
  {
    id: "c01_account_setup",
    stage: "clarity",
    order: 1,
    label: "Create your Sahara account",
    description: "Sign up and verify your email to begin your founder journey.",
    category: "Onboarding",
    completionCriteria: "Account created and email verified",
    estimatedMinutes: 5,
    requiresFred: false,
    autoComplete: true,
  },
  {
    id: "c02_founder_profile",
    stage: "clarity",
    order: 2,
    label: "Complete your founder profile",
    description: "Enter your name, background, industry, and a brief bio so FRED can personalize your experience.",
    category: "Onboarding",
    completionCriteria: "Profile fields (name, industry, bio) are filled",
    estimatedMinutes: 10,
    requiresFred: false,
    autoComplete: true,
  },
  {
    id: "c03_venture_name",
    stage: "clarity",
    order: 3,
    label: "Name your venture",
    description: "Provide a working name for your startup or business idea.",
    category: "Onboarding",
    completionCriteria: "Venture name saved to profile",
    estimatedMinutes: 5,
    requiresFred: false,
    autoComplete: true,
  },
  {
    id: "c04_idea_statement",
    stage: "clarity",
    order: 4,
    label: "Write your one-sentence idea statement",
    description: "Describe your idea in one clear sentence: what it does, who it's for, and why it matters.",
    category: "Idea Definition",
    completionCriteria: "Idea statement saved (minimum 20 characters)",
    estimatedMinutes: 15,
    requiresFred: false,
    autoComplete: true,
  },
  {
    id: "c05_problem_definition",
    stage: "clarity",
    order: 5,
    label: "Define the problem you're solving",
    description: "Clearly articulate the pain point or unmet need your venture addresses.",
    category: "Idea Definition",
    completionCriteria: "Problem statement reviewed by FRED",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c06_personal_why",
    stage: "clarity",
    order: 6,
    label: "Articulate your personal 'why'",
    description: "Explain why you are the right person to solve this problem. What's your unique connection?",
    category: "Founder Readiness",
    completionCriteria: "Personal motivation discussed with FRED",
    estimatedMinutes: 15,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c07_founder_strengths",
    stage: "clarity",
    order: 7,
    label: "Identify your founder strengths",
    description: "List your top 3-5 skills, experiences, or assets that give you an edge in building this venture.",
    category: "Founder Readiness",
    completionCriteria: "Strengths documented in profile",
    estimatedMinutes: 15,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c08_founder_gaps",
    stage: "clarity",
    order: 8,
    label: "Acknowledge your gaps",
    description: "Honestly assess what skills or resources you lack. This shapes your team-building plan.",
    category: "Founder Readiness",
    completionCriteria: "Gap analysis completed with FRED",
    estimatedMinutes: 15,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c09_reality_lens",
    stage: "clarity",
    order: 9,
    label: "Complete your Reality Lens assessment",
    description: "Get an honest multi-perspective evaluation of your idea's viability, market fit, and founder readiness.",
    category: "Assessment",
    completionCriteria: "Reality Lens score generated",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "c10_target_customer_draft",
    stage: "clarity",
    order: 10,
    label: "Draft your target customer description",
    description: "Describe who your ideal customer is — demographics, behaviors, needs.",
    category: "Idea Definition",
    completionCriteria: "Customer description saved",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c11_existing_solutions",
    stage: "clarity",
    order: 11,
    label: "List existing solutions in the market",
    description: "Identify 3-5 alternatives your target customers currently use to solve the same problem.",
    category: "Market Awareness",
    completionCriteria: "At least 3 alternatives listed",
    estimatedMinutes: 20,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "c12_unique_value_draft",
    stage: "clarity",
    order: 12,
    label: "Draft your unique value proposition",
    description: "Write a first draft of what makes your solution different and better than existing alternatives.",
    category: "Idea Definition",
    completionCriteria: "UVP draft saved",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c13_first_fred_session",
    stage: "clarity",
    order: 13,
    label: "Have your first deep conversation with FRED",
    description: "Discuss your idea, motivations, and initial concerns in a substantive coaching session.",
    category: "Coaching",
    completionCriteria: "First chat session completed (minimum 5 messages)",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "c14_mindset_check",
    stage: "clarity",
    order: 14,
    label: "Complete founder mindset check-in",
    description: "Assess your current mental state, energy level, and commitment to the venture.",
    category: "Wellbeing",
    completionCriteria: "Wellbeing check-in completed",
    estimatedMinutes: 10,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c15_cofounding_status",
    stage: "clarity",
    order: 15,
    label: "Define your co-founding situation",
    description: "Are you solo or with co-founders? Define roles, equity expectations, and decision-making.",
    category: "Team",
    completionCriteria: "Co-founder status documented",
    estimatedMinutes: 15,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c16_timeline_goals",
    stage: "clarity",
    order: 16,
    label: "Set your venture timeline and goals",
    description: "Define your 30/60/90 day goals and overall timeline expectations.",
    category: "Planning",
    completionCriteria: "Timeline goals saved to profile",
    estimatedMinutes: 15,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c17_resource_inventory",
    stage: "clarity",
    order: 17,
    label: "Inventory your available resources",
    description: "List what you currently have: savings, time availability, equipment, connections, expertise.",
    category: "Planning",
    completionCriteria: "Resource inventory completed",
    estimatedMinutes: 15,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "c18_risk_awareness",
    stage: "clarity",
    order: 18,
    label: "Identify your top 3 risks",
    description: "What are the biggest risks that could prevent your venture from succeeding?",
    category: "Assessment",
    completionCriteria: "Risk assessment discussed with FRED",
    estimatedMinutes: 15,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c19_commitment_level",
    stage: "clarity",
    order: 19,
    label: "Confirm your commitment level",
    description: "Full-time, part-time, or side project? Be honest about your bandwidth.",
    category: "Founder Readiness",
    completionCriteria: "Commitment level documented",
    estimatedMinutes: 10,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "c20_clarity_review",
    stage: "clarity",
    order: 20,
    label: "Clarity stage review with FRED",
    description: "Review everything you've documented. FRED synthesizes your inputs and confirms you're ready to move to Validation.",
    category: "Milestone",
    completionCriteria: "FRED confirms clarity stage complete",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: false,
  },
]

// ---------------------------------------------------------------------------
// Stage 2: VALIDATION (25 steps)
// Focus: Market research, customer discovery, hypothesis testing
// ---------------------------------------------------------------------------

const validationSteps: JourneyStep[] = [
  {
    id: "v01_customer_persona",
    stage: "validation",
    order: 1,
    label: "Build detailed customer persona",
    description: "Create a comprehensive profile of your ideal customer including demographics, psychographics, and buying behavior.",
    category: "Customer Discovery",
    completionCriteria: "Customer persona document created",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v02_problem_interviews_plan",
    stage: "validation",
    order: 2,
    label: "Plan customer discovery interviews",
    description: "Design 5-10 questions to validate whether your target customers actually experience the problem you identified.",
    category: "Customer Discovery",
    completionCriteria: "Interview script reviewed by FRED",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v03_interview_targets",
    stage: "validation",
    order: 3,
    label: "Identify 10 potential interview targets",
    description: "List 10 people who match your customer persona and could provide validation feedback.",
    category: "Customer Discovery",
    completionCriteria: "At least 10 targets listed",
    estimatedMinutes: 20,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "v04_first_interviews",
    stage: "validation",
    order: 4,
    label: "Conduct first 3 customer interviews",
    description: "Talk to at least 3 potential customers. Document their responses and pain points.",
    category: "Customer Discovery",
    completionCriteria: "3 interview summaries logged",
    estimatedMinutes: 120,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "v05_interview_debrief",
    stage: "validation",
    order: 5,
    label: "Debrief interviews with FRED",
    description: "Review interview findings with FRED. Identify patterns, surprises, and pivot signals.",
    category: "Customer Discovery",
    completionCriteria: "Interview debrief session completed",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v06_market_size_research",
    stage: "validation",
    order: 6,
    label: "Research your total addressable market",
    description: "Estimate TAM, SAM, and SOM for your venture using available data sources.",
    category: "Market Research",
    completionCriteria: "Market size estimates documented",
    estimatedMinutes: 45,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v07_competitor_deep_dive",
    stage: "validation",
    order: 7,
    label: "Analyze top 5 competitors",
    description: "Research your 5 closest competitors: pricing, features, strengths, weaknesses, market share.",
    category: "Market Research",
    completionCriteria: "Competitive analysis completed",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "v08_positioning_statement",
    stage: "validation",
    order: 8,
    label: "Refine your positioning statement",
    description: "Using market research, create a positioning statement: For [target], who [need], [product] is a [category] that [benefit].",
    category: "Positioning",
    completionCriteria: "Positioning statement approved by FRED",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v09_value_hypothesis",
    stage: "validation",
    order: 9,
    label: "Define your value hypothesis",
    description: "State the core assumption about why customers will use your product. Make it testable.",
    category: "Hypothesis",
    completionCriteria: "Value hypothesis documented",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v10_growth_hypothesis",
    stage: "validation",
    order: 10,
    label: "Define your growth hypothesis",
    description: "State how you believe new users will discover your product. Identify your primary growth channel.",
    category: "Hypothesis",
    completionCriteria: "Growth hypothesis documented",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v11_revenue_model_draft",
    stage: "validation",
    order: 11,
    label: "Draft initial revenue model",
    description: "How will you make money? Define pricing strategy, revenue streams, and initial unit economics.",
    category: "Business Model",
    completionCriteria: "Revenue model draft saved",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v12_cost_structure",
    stage: "validation",
    order: 12,
    label: "Estimate your cost structure",
    description: "List fixed and variable costs. Estimate monthly burn rate for the first 6 months.",
    category: "Business Model",
    completionCriteria: "Cost structure documented",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "v13_mvp_definition",
    stage: "validation",
    order: 13,
    label: "Define your minimum viable product",
    description: "What is the smallest version of your product that can test your value hypothesis?",
    category: "Product",
    completionCriteria: "MVP scope documented with FRED",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v14_validation_experiment",
    stage: "validation",
    order: 14,
    label: "Design a validation experiment",
    description: "Create a low-cost experiment to test demand before building. Landing page, pre-order, waitlist, etc.",
    category: "Validation",
    completionCriteria: "Experiment plan approved by FRED",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v15_run_experiment",
    stage: "validation",
    order: 15,
    label: "Run your validation experiment",
    description: "Execute your experiment and collect data. Track signups, interest, or pre-orders.",
    category: "Validation",
    completionCriteria: "Experiment results documented",
    estimatedMinutes: 120,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "v16_experiment_analysis",
    stage: "validation",
    order: 16,
    label: "Analyze experiment results with FRED",
    description: "Review your experiment data. Did it validate or invalidate your hypothesis? What's next?",
    category: "Validation",
    completionCriteria: "Analysis session completed",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v17_pivot_or_proceed",
    stage: "validation",
    order: 17,
    label: "Make pivot-or-proceed decision",
    description: "Based on evidence, decide: proceed as planned, pivot the approach, or abandon and restart.",
    category: "Decision",
    completionCriteria: "Decision documented with FRED",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v18_coaching_session_5",
    stage: "validation",
    order: 18,
    label: "Complete 5 total coaching conversations",
    description: "By now you should have had at least 5 substantive conversations with FRED.",
    category: "Coaching",
    completionCriteria: "5 chat sessions completed",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "v19_legal_structure",
    stage: "validation",
    order: 19,
    label: "Research legal entity options",
    description: "Understand LLC vs C-Corp vs S-Corp. Discuss with FRED which structure fits your goals.",
    category: "Legal",
    completionCriteria: "Legal structure discussion completed",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v20_ip_assessment",
    stage: "validation",
    order: 20,
    label: "Assess intellectual property needs",
    description: "Do you need patents, trademarks, or copyrights? Identify any IP risks or opportunities.",
    category: "Legal",
    completionCriteria: "IP assessment completed",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v21_advisory_needs",
    stage: "validation",
    order: 21,
    label: "Identify advisory board needs",
    description: "What expertise gaps could advisors fill? List 3 types of advisors that would add value.",
    category: "Team",
    completionCriteria: "Advisory needs documented",
    estimatedMinutes: 15,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v22_brand_name_check",
    stage: "validation",
    order: 22,
    label: "Check brand name availability",
    description: "Verify your venture name is available as a domain, social handles, and isn't trademarked.",
    category: "Branding",
    completionCriteria: "Brand name availability confirmed",
    estimatedMinutes: 20,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "v23_elevator_pitch",
    stage: "validation",
    order: 23,
    label: "Craft your 60-second elevator pitch",
    description: "Create a compelling verbal pitch you can deliver in under 60 seconds.",
    category: "Communication",
    completionCriteria: "Elevator pitch reviewed by FRED",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v24_validation_scorecard",
    stage: "validation",
    order: 24,
    label: "Complete validation scorecard",
    description: "Rate your confidence level (1-10) across: problem, customer, solution, market, team.",
    category: "Assessment",
    completionCriteria: "Scorecard completed",
    estimatedMinutes: 15,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "v25_validation_review",
    stage: "validation",
    order: 25,
    label: "Validation stage review with FRED",
    description: "Comprehensive review of all validation work. FRED confirms readiness to enter Build stage.",
    category: "Milestone",
    completionCriteria: "FRED confirms validation stage complete",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
]

// ---------------------------------------------------------------------------
// Stage 3: BUILD (30 steps)
// Focus: Product development, branding, operational foundation
// ---------------------------------------------------------------------------

const buildSteps: JourneyStep[] = [
  {
    id: "b01_brand_identity",
    stage: "build",
    order: 1,
    label: "Define brand identity basics",
    description: "Set your brand's mission, vision, values, and personality traits.",
    category: "Branding",
    completionCriteria: "Brand identity document created",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b02_visual_identity",
    stage: "build",
    order: 2,
    label: "Create visual identity guidelines",
    description: "Define colors, fonts, logo direction, and visual style for your brand.",
    category: "Branding",
    completionCriteria: "Visual identity documented",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b03_brand_voice",
    stage: "build",
    order: 3,
    label: "Establish brand voice and messaging",
    description: "Define how your brand speaks: tone, vocabulary, do/don't examples.",
    category: "Branding",
    completionCriteria: "Brand voice guide created",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b04_website_plan",
    stage: "build",
    order: 4,
    label: "Plan your web presence",
    description: "Define website structure, key pages, and content priorities. Domain secured.",
    category: "Digital Presence",
    completionCriteria: "Website plan documented",
    estimatedMinutes: 25,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b05_social_setup",
    stage: "build",
    order: 5,
    label: "Set up social media profiles",
    description: "Create consistent profiles on 2-3 key platforms where your audience lives.",
    category: "Digital Presence",
    completionCriteria: "Social profiles created",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b06_product_roadmap",
    stage: "build",
    order: 6,
    label: "Create product roadmap",
    description: "Define phases: MVP, v1, v2. Prioritize features by customer impact and feasibility.",
    category: "Product",
    completionCriteria: "Product roadmap document created",
    estimatedMinutes: 45,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b07_tech_stack_decision",
    stage: "build",
    order: 7,
    label: "Choose your technology approach",
    description: "Build vs buy vs no-code. Discuss trade-offs with FRED based on your resources.",
    category: "Product",
    completionCriteria: "Technology decision documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b08_mvp_build_plan",
    stage: "build",
    order: 8,
    label: "Create MVP build plan",
    description: "Break your MVP into tasks with timelines, owners, and dependencies.",
    category: "Product",
    completionCriteria: "Build plan with milestones created",
    estimatedMinutes: 45,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b09_user_flow_design",
    stage: "build",
    order: 9,
    label: "Design core user flows",
    description: "Map the key journeys: signup, first use, core action, repeat engagement.",
    category: "Product",
    completionCriteria: "User flows documented",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b10_prototype_wireframe",
    stage: "build",
    order: 10,
    label: "Create prototype or wireframes",
    description: "Build low-fidelity mockups of your key screens. Use Figma, paper, or no-code tools.",
    category: "Product",
    completionCriteria: "Wireframes created",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b11_business_plan_draft",
    stage: "build",
    order: 11,
    label: "Draft business plan summary",
    description: "Write a 2-3 page business plan covering problem, solution, market, model, team, and ask.",
    category: "Strategy",
    completionCriteria: "Business plan document created",
    estimatedMinutes: 60,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "b12_financial_projections",
    stage: "build",
    order: 12,
    label: "Create 12-month financial projections",
    description: "Build revenue, expense, and cash flow projections for the first year.",
    category: "Finance",
    completionCriteria: "Financial projections documented",
    estimatedMinutes: 60,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b13_pricing_strategy",
    stage: "build",
    order: 13,
    label: "Finalize pricing strategy",
    description: "Set your pricing model: freemium, subscription, one-time, usage-based. Test price sensitivity.",
    category: "Business Model",
    completionCriteria: "Pricing strategy documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b14_entity_formation",
    stage: "build",
    order: 14,
    label: "Form your legal entity",
    description: "Incorporate your business. File necessary paperwork for your chosen structure.",
    category: "Legal",
    completionCriteria: "Legal entity formation confirmed",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b15_banking_setup",
    stage: "build",
    order: 15,
    label: "Set up business banking",
    description: "Open a business bank account. Separate personal and business finances from day one.",
    category: "Finance",
    completionCriteria: "Business bank account opened",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b16_accounting_setup",
    stage: "build",
    order: 16,
    label: "Set up basic accounting",
    description: "Choose an accounting tool (QuickBooks, Wave, etc.) and set up chart of accounts.",
    category: "Finance",
    completionCriteria: "Accounting system configured",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b17_team_hiring_plan",
    stage: "build",
    order: 17,
    label: "Create team hiring plan",
    description: "Define roles needed for MVP: who to hire first, contractor vs full-time, budget.",
    category: "Team",
    completionCriteria: "Hiring plan documented",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b18_equity_structure",
    stage: "build",
    order: 18,
    label: "Define equity and compensation structure",
    description: "Set founder equity splits, vesting schedules, and early employee option pool.",
    category: "Legal",
    completionCriteria: "Equity structure documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b19_operations_setup",
    stage: "build",
    order: 19,
    label: "Set up operational tools",
    description: "Choose and configure tools for communication, project management, and file sharing.",
    category: "Operations",
    completionCriteria: "Core tools configured",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b20_mvp_development",
    stage: "build",
    order: 20,
    label: "Begin MVP development",
    description: "Start building your MVP according to your build plan. Track progress weekly.",
    category: "Product",
    completionCriteria: "MVP development started (first milestone met)",
    estimatedMinutes: 240,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b21_beta_testing_plan",
    stage: "build",
    order: 21,
    label: "Plan beta testing program",
    description: "Define beta criteria: who tests, how long, what metrics, how to collect feedback.",
    category: "Product",
    completionCriteria: "Beta test plan documented",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b22_content_strategy",
    stage: "build",
    order: 22,
    label: "Create content marketing strategy",
    description: "Plan your content: topics, formats, publishing cadence, distribution channels.",
    category: "Marketing",
    completionCriteria: "Content strategy documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b23_launch_landing_page",
    stage: "build",
    order: 23,
    label: "Build pre-launch landing page",
    description: "Create a landing page to capture early interest: waitlist, email signups, or pre-orders.",
    category: "Digital Presence",
    completionCriteria: "Landing page live",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b24_pitch_deck_v1",
    stage: "build",
    order: 24,
    label: "Create pitch deck v1",
    description: "Build your first complete pitch deck: problem, solution, market, model, team, ask.",
    category: "Fundraising",
    completionCriteria: "Pitch deck uploaded",
    estimatedMinutes: 120,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "b25_pitch_deck_review",
    stage: "build",
    order: 25,
    label: "Review pitch deck with FRED",
    description: "Get detailed feedback on every slide of your pitch deck from FRED's investor perspective.",
    category: "Fundraising",
    completionCriteria: "Pitch deck reviewed with score generated",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "b26_readiness_baseline",
    stage: "build",
    order: 26,
    label: "Complete investor readiness assessment",
    description: "Get your first investor readiness score to establish a baseline for improvement.",
    category: "Fundraising",
    completionCriteria: "Investor readiness score generated",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "b27_partnerships_research",
    stage: "build",
    order: 27,
    label: "Research strategic partnerships",
    description: "Identify 3-5 potential partners who could help with distribution, technology, or credibility.",
    category: "Business Development",
    completionCriteria: "Partnership opportunities documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b28_metrics_framework",
    stage: "build",
    order: 28,
    label: "Define your key metrics",
    description: "Identify your North Star metric and 3-5 supporting KPIs to track from day one.",
    category: "Analytics",
    completionCriteria: "Metrics framework documented",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "b29_customer_support_plan",
    stage: "build",
    order: 29,
    label: "Plan customer support approach",
    description: "How will you handle customer inquiries, bugs, and feedback? Define SLAs and tools.",
    category: "Operations",
    completionCriteria: "Support plan documented",
    estimatedMinutes: 20,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "b30_build_review",
    stage: "build",
    order: 30,
    label: "Build stage review with FRED",
    description: "Comprehensive review of all build outputs. FRED assesses readiness for Launch stage.",
    category: "Milestone",
    completionCriteria: "FRED confirms build stage complete",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
]

// ---------------------------------------------------------------------------
// Stage 4: LAUNCH (25 steps)
// Focus: Go-to-market, fundraising preparation, first customers
// ---------------------------------------------------------------------------

const launchSteps: JourneyStep[] = [
  {
    id: "l01_launch_plan",
    stage: "launch",
    order: 1,
    label: "Create launch plan",
    description: "Define launch strategy: timeline, channels, targets, success metrics.",
    category: "Go-to-Market",
    completionCriteria: "Launch plan documented",
    estimatedMinutes: 45,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l02_gtm_channels",
    stage: "launch",
    order: 2,
    label: "Prioritize go-to-market channels",
    description: "Rank your top 3 customer acquisition channels and plan experiments for each.",
    category: "Go-to-Market",
    completionCriteria: "Channel prioritization documented",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l03_marketing_budget",
    stage: "launch",
    order: 3,
    label: "Set marketing budget",
    description: "Allocate initial marketing spend across channels. Start small, measure, scale what works.",
    category: "Marketing",
    completionCriteria: "Marketing budget set",
    estimatedMinutes: 20,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l04_launch_content",
    stage: "launch",
    order: 4,
    label: "Prepare launch content",
    description: "Create announcement post, demo video, FAQ page, and initial content pieces.",
    category: "Marketing",
    completionCriteria: "Launch content prepared",
    estimatedMinutes: 90,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l05_beta_recruit",
    stage: "launch",
    order: 5,
    label: "Recruit beta users",
    description: "Get 10-20 beta users to test your MVP and provide structured feedback.",
    category: "Product",
    completionCriteria: "10+ beta users onboarded",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l06_beta_feedback",
    stage: "launch",
    order: 6,
    label: "Collect and analyze beta feedback",
    description: "Gather feedback from beta users. Identify critical bugs, UX issues, and feature requests.",
    category: "Product",
    completionCriteria: "Beta feedback summary completed",
    estimatedMinutes: 45,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l07_iterate_mvp",
    stage: "launch",
    order: 7,
    label: "Iterate on MVP based on feedback",
    description: "Fix critical issues and make highest-impact improvements before public launch.",
    category: "Product",
    completionCriteria: "MVP iteration completed",
    estimatedMinutes: 120,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l08_pitch_refine",
    stage: "launch",
    order: 8,
    label: "Refine pitch deck (target score >= 60)",
    description: "Polish your pitch deck based on beta results and FRED's feedback until you score 60+.",
    category: "Fundraising",
    completionCriteria: "Pitch deck score >= 60",
    estimatedMinutes: 60,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "l09_readiness_70",
    stage: "launch",
    order: 9,
    label: "Achieve investor readiness score >= 70",
    description: "Improve your overall investor readiness score to at least 70 out of 100.",
    category: "Fundraising",
    completionCriteria: "Investor readiness score >= 70",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: true,
  },
  {
    id: "l10_investor_story",
    stage: "launch",
    order: 10,
    label: "Craft your investor narrative",
    description: "Build a compelling story: why now, why you, why this market, what's the big vision.",
    category: "Fundraising",
    completionCriteria: "Investor narrative reviewed by FRED",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l11_financial_model",
    stage: "launch",
    order: 11,
    label: "Build 3-year financial model",
    description: "Extend projections to 3 years. Model scenarios: conservative, base, optimistic.",
    category: "Finance",
    completionCriteria: "3-year financial model documented",
    estimatedMinutes: 90,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l12_investor_list",
    stage: "launch",
    order: 12,
    label: "Build target investor list",
    description: "Research and list 20-30 investors who invest in your stage, sector, and geography.",
    category: "Fundraising",
    completionCriteria: "Investor list with 20+ entries created",
    estimatedMinutes: 60,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l13_warm_intros",
    stage: "launch",
    order: 13,
    label: "Map warm introduction paths",
    description: "For each target investor, identify potential warm intro paths through your network.",
    category: "Fundraising",
    completionCriteria: "Intro paths mapped for 10+ investors",
    estimatedMinutes: 45,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l14_pitch_practice",
    stage: "launch",
    order: 14,
    label: "Practice your pitch 5 times",
    description: "Rehearse your full pitch with FRED. Get feedback on clarity, pacing, and persuasiveness.",
    category: "Communication",
    completionCriteria: "5 pitch practice sessions logged",
    estimatedMinutes: 75,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l15_objection_handling",
    stage: "launch",
    order: 15,
    label: "Prepare investor objection responses",
    description: "Anticipate top 10 investor objections and prepare compelling responses.",
    category: "Fundraising",
    completionCriteria: "Objection responses documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l16_data_room",
    stage: "launch",
    order: 16,
    label: "Prepare due diligence data room",
    description: "Organize key documents: incorporation, cap table, financials, team bios, IP summary.",
    category: "Fundraising",
    completionCriteria: "Data room set up",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l17_first_customers",
    stage: "launch",
    order: 17,
    label: "Acquire first 10 paying customers",
    description: "Get your first paying customers through direct outreach, network, or launch channels.",
    category: "Sales",
    completionCriteria: "10 paying customers acquired",
    estimatedMinutes: 240,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l18_customer_feedback_loop",
    stage: "launch",
    order: 18,
    label: "Establish customer feedback loop",
    description: "Set up systematic processes to collect, analyze, and act on customer feedback.",
    category: "Operations",
    completionCriteria: "Feedback loop process documented",
    estimatedMinutes: 25,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l19_unit_economics",
    stage: "launch",
    order: 19,
    label: "Calculate actual unit economics",
    description: "With real data, calculate CAC, LTV, churn, and payback period.",
    category: "Finance",
    completionCriteria: "Unit economics documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l20_pr_strategy",
    stage: "launch",
    order: 20,
    label: "Develop PR/media strategy",
    description: "Identify media outlets, journalists, and communities where your audience pays attention.",
    category: "Marketing",
    completionCriteria: "PR strategy documented",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "l21_network_building",
    stage: "launch",
    order: 21,
    label: "Activate professional network",
    description: "Reach out to mentors, peers, and industry contacts. Join relevant communities.",
    category: "Business Development",
    completionCriteria: "Networking plan executed",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l22_legal_compliance",
    stage: "launch",
    order: 22,
    label: "Complete legal compliance checklist",
    description: "Privacy policy, terms of service, necessary licenses, data protection compliance.",
    category: "Legal",
    completionCriteria: "Legal compliance checklist completed",
    estimatedMinutes: 45,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l23_insurance_review",
    stage: "launch",
    order: 23,
    label: "Review insurance needs",
    description: "Assess liability, professional, and cyber insurance requirements for your venture.",
    category: "Legal",
    completionCriteria: "Insurance review completed",
    estimatedMinutes: 20,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l24_public_launch",
    stage: "launch",
    order: 24,
    label: "Execute public launch",
    description: "Go live publicly. Announce across all channels. Track launch day metrics.",
    category: "Go-to-Market",
    completionCriteria: "Public launch completed",
    estimatedMinutes: 120,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "l25_launch_review",
    stage: "launch",
    order: 25,
    label: "Launch stage review with FRED",
    description: "Review launch results, early metrics, and lessons. FRED assesses readiness for Grow stage.",
    category: "Milestone",
    completionCriteria: "FRED confirms launch stage complete",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
]

// ---------------------------------------------------------------------------
// Stage 5: GROW (20 steps)
// Focus: Scaling, optimization, fundraising, team growth
// ---------------------------------------------------------------------------

const growSteps: JourneyStep[] = [
  {
    id: "g01_growth_strategy",
    stage: "grow",
    order: 1,
    label: "Define growth strategy",
    description: "Based on launch data, define your primary growth strategy for the next 6 months.",
    category: "Strategy",
    completionCriteria: "Growth strategy documented",
    estimatedMinutes: 45,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g02_channel_optimization",
    stage: "grow",
    order: 2,
    label: "Optimize acquisition channels",
    description: "Double down on what's working. Kill what isn't. Optimize conversion funnels.",
    category: "Growth",
    completionCriteria: "Channel optimization plan documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g03_retention_strategy",
    stage: "grow",
    order: 3,
    label: "Build retention strategy",
    description: "Analyze churn, identify retention drivers, and build engagement loops.",
    category: "Growth",
    completionCriteria: "Retention strategy documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g04_first_hire",
    stage: "grow",
    order: 4,
    label: "Make your first key hire",
    description: "Hire your most critical team member based on your biggest gap or opportunity.",
    category: "Team",
    completionCriteria: "First hire made or in progress",
    estimatedMinutes: 120,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g05_culture_values",
    stage: "grow",
    order: 5,
    label: "Define company culture and values",
    description: "Articulate the culture you're building before you grow past 5 people.",
    category: "Team",
    completionCriteria: "Culture document created",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g06_process_automation",
    stage: "grow",
    order: 6,
    label: "Automate key processes",
    description: "Identify repetitive tasks and automate: onboarding, invoicing, reporting, support.",
    category: "Operations",
    completionCriteria: "3+ processes automated",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "g07_data_analytics",
    stage: "grow",
    order: 7,
    label: "Set up analytics dashboard",
    description: "Build a dashboard tracking your North Star metric and key KPIs in real time.",
    category: "Analytics",
    completionCriteria: "Analytics dashboard configured",
    estimatedMinutes: 45,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "g08_fundraise_decision",
    stage: "grow",
    order: 8,
    label: "Make fundraising decision",
    description: "Evaluate: do you need to raise? Bootstrap? Revenue-based financing? Discuss with FRED.",
    category: "Fundraising",
    completionCriteria: "Fundraising decision documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g09_investor_outreach",
    stage: "grow",
    order: 9,
    label: "Begin investor outreach",
    description: "Start reaching out to your target investor list. Track responses and meetings.",
    category: "Fundraising",
    completionCriteria: "Outreach to 10+ investors initiated",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "g10_boardy_matching",
    stage: "grow",
    order: 10,
    label: "Activate Boardy fund matching",
    description: "Connect with potential investors through Sahara's network matching system.",
    category: "Fundraising",
    completionCriteria: "Boardy matching activated",
    estimatedMinutes: 15,
    requiresFred: false,
    autoComplete: true,
  },
  {
    id: "g11_product_iteration",
    stage: "grow",
    order: 11,
    label: "Plan next product iteration",
    description: "Based on customer data, plan v2 features that drive retention and expansion.",
    category: "Product",
    completionCriteria: "v2 roadmap documented",
    estimatedMinutes: 45,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g12_pricing_optimization",
    stage: "grow",
    order: 12,
    label: "Optimize pricing",
    description: "Test pricing changes based on actual willingness-to-pay data. Consider tiers.",
    category: "Business Model",
    completionCriteria: "Pricing optimization documented",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g13_partnership_execution",
    stage: "grow",
    order: 13,
    label: "Execute first strategic partnership",
    description: "Formalize at least one partnership: co-marketing, integration, or distribution.",
    category: "Business Development",
    completionCriteria: "Partnership agreement in place",
    estimatedMinutes: 60,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "g14_community_building",
    stage: "grow",
    order: 14,
    label: "Build customer community",
    description: "Create a space for customers to connect, share, and become advocates.",
    category: "Community",
    completionCriteria: "Community launched",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "g15_referral_program",
    stage: "grow",
    order: 15,
    label: "Create referral program",
    description: "Design and launch a customer referral program to drive word-of-mouth growth.",
    category: "Growth",
    completionCriteria: "Referral program launched",
    estimatedMinutes: 30,
    requiresFred: false,
    autoComplete: false,
  },
  {
    id: "g16_scaling_plan",
    stage: "grow",
    order: 16,
    label: "Create scaling plan",
    description: "Document what needs to change to 10x your current capacity: team, tech, processes.",
    category: "Strategy",
    completionCriteria: "Scaling plan documented",
    estimatedMinutes: 45,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g17_advisory_board",
    stage: "grow",
    order: 17,
    label: "Assemble advisory board",
    description: "Recruit 2-3 advisors who bring expertise, credibility, and connections.",
    category: "Team",
    completionCriteria: "Advisory board formed",
    estimatedMinutes: 60,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g18_milestone_tracker",
    stage: "grow",
    order: 18,
    label: "Set next 6-month milestones",
    description: "Define specific, measurable milestones for the next 6 months.",
    category: "Planning",
    completionCriteria: "Milestones documented",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g19_investor_update",
    stage: "grow",
    order: 19,
    label: "Write first investor update",
    description: "Practice transparency: write an investor-style update even if not yet funded.",
    category: "Communication",
    completionCriteria: "Investor update written",
    estimatedMinutes: 25,
    requiresFred: true,
    autoComplete: false,
  },
  {
    id: "g20_grow_review",
    stage: "grow",
    order: 20,
    label: "Journey completion review with FRED",
    description: "Comprehensive review of your entire journey. Celebrate progress, identify next challenges, plan forward.",
    category: "Milestone",
    completionCriteria: "FRED confirms full journey complete",
    estimatedMinutes: 30,
    requiresFred: true,
    autoComplete: false,
  },
]

// ---------------------------------------------------------------------------
// Export: All 120 steps
// ---------------------------------------------------------------------------

export const IDEAPROS_JOURNEY_STEPS: JourneyStep[] = [
  ...claritySteps,
  ...validationSteps,
  ...buildSteps,
  ...launchSteps,
  ...growSteps,
]

/** Steps grouped by stage for easy lookup */
export const JOURNEY_STEPS_BY_STAGE: Record<OasesStage, JourneyStep[]> = {
  clarity: claritySteps,
  validation: validationSteps,
  build: buildSteps,
  launch: launchSteps,
  grow: growSteps,
}

/** Total step count per stage */
export const STAGE_STEP_COUNTS: Record<OasesStage, number> = {
  clarity: claritySteps.length,
  validation: validationSteps.length,
  build: buildSteps.length,
  launch: launchSteps.length,
  grow: growSteps.length,
}

/** Categories across all stages */
export const JOURNEY_CATEGORIES = Array.from(
  new Set(IDEAPROS_JOURNEY_STEPS.map((s) => s.category))
).sort()
