import { NextRequest, NextResponse } from "next/server";
import { getUserInsights, dismissInsight } from "@/lib/ai/insight-extractor";
import { requireAuth } from "@/lib/auth";

/**
 * GET /api/journey/insights
 * List user's AI-generated insights with optional filters
 *
 * SECURITY: Requires authentication - userId from server-side session
 */
export async function GET(request: NextRequest) {
  try {
    // SECURITY: Get userId from server-side session (not from client headers!)
    const userId = await requireAuth();

    const { searchParams } = new URL(request.url);
    const sourceType = searchParams.get("source_type") || undefined;
    const insightType = searchParams.get("insight_type") || undefined;
    const minImportance = searchParams.get("min_importance")
      ? parseInt(searchParams.get("min_importance")!, 10)
      : undefined;
    const limit = searchParams.get("limit")
      ? parseInt(searchParams.get("limit")!, 10)
      : 50;
    const pinnedOnly = searchParams.get("pinned") === "true";

    const insights = await getUserInsights(userId, {
      sourceType,
      insightType,
      minImportance,
      limit,
    });

    // Filter by pinned if requested (pinned = not dismissed in UI terms)
    const filteredInsights = pinnedOnly
      ? insights.filter((i) => !i.isDismissed)
      : insights;

    return NextResponse.json({
      success: true,
      data: filteredInsights,
      meta: {
        count: filteredInsights.length,
        limit,
        filters: { sourceType, insightType, minImportance, pinnedOnly }
      }
    });
  } catch (error) {
    console.error("[GET /api/journey/insights]", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch insights" },
      { status: 500 }
    );
  }
}

/**
 * POST /api/journey/insights
 * Not implemented - insights are auto-generated by AI analyzers
 * Use the insight-extractor directly in AI pipelines
 */
export async function POST(request: NextRequest) {
  return NextResponse.json(
    {
      success: false,
      error: "Insights are auto-generated. Use AI analyzers to create insights."
    },
    { status: 405 }
  );
}

/**
 * PATCH /api/journey/insights
 * Update insight (pin/unpin, dismiss)
 * Body: { insightId: string, action: "pin" | "unpin" | "dismiss" }
 *
 * SECURITY: Requires authentication - userId from server-side session
 */
export async function PATCH(request: NextRequest) {
  try {
    // SECURITY: Get userId from server-side session (not from client headers!)
    const userId = await requireAuth();

    const body = await request.json();
    const { insightId, action } = body;

    if (!insightId || !action) {
      return NextResponse.json(
        { success: false, error: "Missing insightId or action" },
        { status: 400 }
      );
    }

    if (!["pin", "unpin", "dismiss"].includes(action)) {
      return NextResponse.json(
        { success: false, error: "Invalid action. Must be: pin, unpin, dismiss" },
        { status: 400 }
      );
    }

    // For dismiss action, use the dismissInsight function
    if (action === "dismiss") {
      await dismissInsight(userId, insightId);
      return NextResponse.json({
        success: true,
        message: "Insight dismissed"
      });
    }

    // For pin/unpin, we need to update is_pinned field
    // Note: The insight-extractor doesn't have a pin function, so we do it directly
    const { sql } = await import("@/lib/db/neon");

    if (action === "pin") {
      await sql`
        UPDATE ai_insights
        SET is_pinned = true
        WHERE id = ${insightId} AND user_id = ${userId}
      `;
    } else if (action === "unpin") {
      await sql`
        UPDATE ai_insights
        SET is_pinned = false
        WHERE id = ${insightId} AND user_id = ${userId}
      `;
    }

    return NextResponse.json({
      success: true,
      message: `Insight ${action}ned`
    });
  } catch (error) {
    console.error("[PATCH /api/journey/insights]", error);
    return NextResponse.json(
      { success: false, error: "Failed to update insight" },
      { status: 500 }
    );
  }
}
