import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import { getUserTier } from "@/lib/api/tier-middleware";
import { UserTier, canAccessFeature } from "@/lib/constants";

/**
 * POST /api/fred/pitch-deck/export
 *
 * Exports a generated pitch deck draft as a simple text-based PDF.
 * Uses @react-pdf/renderer which is already in the project dependencies.
 *
 * For v1, returns a clean text document. Future versions will use
 * react-pdf for branded slide layouts.
 */
export async function POST(req: NextRequest) {
  try {
    const userId = await requireAuth();
    const userTier = await getUserTier(userId);

    if (!canAccessFeature(userTier, UserTier.PRO)) {
      return NextResponse.json(
        { success: false, error: "Pro tier required" },
        { status: 403 }
      );
    }

    const body = await req.json();
    const deck = body.deck;

    if (!deck || !deck.slides || !Array.isArray(deck.slides)) {
      return NextResponse.json(
        { success: false, error: "Invalid deck data" },
        { status: 400 }
      );
    }

    // Generate a clean text export (v1 - simple text format)
    // Future: use @react-pdf/renderer for branded PDF
    const lines: string[] = [];
    lines.push(deck.companyName?.toUpperCase() || "PITCH DECK");
    lines.push(deck.tagline || "");
    lines.push("=".repeat(60));
    lines.push("");

    if (deck.investorReadinessScore !== null && deck.investorReadinessScore !== undefined) {
      lines.push(`Investor Readiness Score: ${deck.investorReadinessScore}/100`);
      lines.push("");
    }

    for (let i = 0; i < deck.slides.length; i++) {
      const slide = deck.slides[i];
      lines.push(`--- SLIDE ${i + 1}: ${slide.title} ---`);
      lines.push(`Section: ${slide.type}`);
      lines.push("");

      for (const bullet of slide.bullets) {
        lines.push(`  * ${bullet}`);
      }

      if (slide.speakerNotes) {
        lines.push("");
        lines.push(`  [Speaker Notes] ${slide.speakerNotes}`);
      }

      lines.push("");
      lines.push("");
    }

    lines.push("=".repeat(60));
    lines.push(`Generated by Sahara / FRED on ${new Date().toLocaleDateString()}`);

    const content = lines.join("\n");
    const encoder = new TextEncoder();
    const data = encoder.encode(content);

    return new NextResponse(data, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="${(deck.companyName || "pitch-deck").replace(/\s+/g, "-").toLowerCase()}-pitch-deck.txt"`,
      },
    });
  } catch (error) {
    if (error instanceof NextResponse) return error;

    console.error("[pitch-deck/export] Error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to export pitch deck" },
      { status: 500 }
    );
  }
}
